# Generated by Django 3.0.2 on 2020-02-01 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeraccessrequest',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
