# Generated by Django 3.0.2 on 2020-02-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_request', '0003_auto_20200203_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeraccessrequest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
