# Generated by Django 3.0.2 on 2020-02-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_request', '0004_auto_20200203_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeraccessrequest',
            name='product_domains',
        ),
    ]
