# Generated by Django 3.0.2 on 2020-02-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_request', '0005_remove_registeraccessrequest_product_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeraccessrequest',
            name='product_domains',
            field=models.ManyToManyField(to='register_request.ProductDomain'),
        ),
    ]
