# Generated by Django 3.0.2 on 2020-02-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_request', '0006_registeraccessrequest_product_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorisedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.BooleanField()),
                ('product_domains', models.ManyToManyField(to='register_request.ProductDomain')),
            ],
        ),
    ]
