# Generated by Django 3.0.2 on 2020-02-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_request', '0007_authoriseduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoriseduser',
            name='email',
            field=models.EmailField(default='aditya@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='authoriseduser',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
