# Generated by Django 3.0.2 on 2020-02-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_request', '0009_auto_20200204_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoriseduser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='registeraccessrequest',
            name='designation',
            field=models.CharField(choices=[('Engineering Manager', 'Engineering Manager'), ('Team Lead', 'Team Lead')], max_length=200),
        ),
        migrations.AlterField(
            model_name='registeraccessrequest',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
