# Generated by Django 3.0.2 on 2020-02-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_request', '0010_auto_20200204_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ceated_date', models.DateTimeField()),
                ('approved_date', models.DateTimeField(auto_now_add=True)),
                ('product_domains', models.ManyToManyField(to='register_request.ProductDomain')),
            ],
        ),
    ]
