# Generated by Django 3.0.2 on 2020-02-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_request', '0011_requesthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesthistory',
            name='ceated_date',
        ),
    ]
