# Generated by Django 3.0.2 on 2020-02-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDomainIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('product_domain', models.CharField(blank=True, max_length=200, null=True)),
                ('business_unit', models.CharField(blank=True, max_length=200, null=True)),
                ('eng_manager', models.EmailField(blank=True, max_length=200, null=True)),
                ('team_lead', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
